version: '3'

services:
  nginx-entry:
    build: .
    volumes:
      - /opt/sites/:/opt/sites/
    networks:
      - nginx-entry
    ports:
      - "80:80"
      - "443:443"
      - "3000:3000"

networks:
  nginx-entry:
